server:
  port: 9527

spring:
  application:
    name: microservice-springcloud-zuul

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: microservice_springcloud-zuul9527

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  ignored-services: "*"
  routes:
    dept-route:
      serviceId: MICROSERVICE-SPRINGCLOUD-DEPT
      path: /dept/**

info:
  app:
    name: mySpringCloud
  company:
    name: myProject
  build:
    artifactId: $project.artifactId$
    version: $project.version$
